backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: src/assets
public_folder: ../../assets/

collections:
  - name: "component"
    label: "Component"
    folder: "src/markdowns/components"
    create: true
    slug: "{{path}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "components",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - {
          label: Steps,
          name: "steps",
          widget: "list",
          fields:
            [
              { label: description, name: description, widget: text },
              { label: Code, name: code, widget: code },
              { label: Note, name: note, widget: text, required: false, output_code_only: true },
              { label: Body, name: body, widget: markdown},
            ],
        }
