backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: src/assets
public_folder: ../../assets/

collections:
  - name: "news"
    label: "News"
    folder: "src/markdowns/jfeem-news"
    create: true
    slug: "identifier"
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "news",
        }
      - {
          label: "Include in recent news?",
          name: "recent",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
            
              