backend:
  name: git-gateway
  branch: main

local_backend: false
media_folder: src/assets
public_folder: ../../assets/

collections:
  - name: "component"
    label: "Component"
    folder: "src/markdowns/components"
    create: true
    slug: "identifier"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "news",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Identifier", name: "identifier", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
            
              